
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: portfolio-api_development

test:
  <<: *default
  database: portfolio-api_test

production:
  <<: *default
  database: portfolio-api_production
  username: portfolio-api
  password: <%= ENV['PORTFOLIO-API_DATABASE_PASSWORD'] %>
